export const theme = {
  colors: {
    // Cores do tema escuro (padrão)
    primary: '#7c4dff',
    primaryLight: '#b47cff',
    primaryDark: '#3f1dcb',
    secondary: '#00e5ff',
    dark: '#121212',
    darker: '#0a0a0a',
    darkLight: '#1e1e1e',
    success: '#00c853',
    danger: '#ff3d00',
    warning: '#ffab00',
    info: '#00b0ff',
    text: '#ffffff',
    textDim: '#b3b3b3',
    textSecondary: '#b0b0b0',
    textMuted: '#808080',
    border: '#333333',
  },
  fonts: {
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semibold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    card: 12,
    input: 6,
    button: 8,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 8,
    },
  },
};

// Cores do tema claro — melhoradas para melhor contraste e legibilidade
export const lightThemeColors = {
  primary: '#6c3fff',
  primaryLight: '#9c6fff',
  primaryDark: '#3f1dcb',
  secondary: '#00b8d9',
  success: '#00a844',
  danger: '#d32f2f',
  warning: '#e65100',
  info: '#0077c2',
  background: '#f0f2f5',
  surface: '#ffffff',
  surfaceDark: '#e8eaf0',
  text: '#1a1a2e',
  textDim: '#4a4a6a',
  textSecondary: '#5c5c7a',
  textMuted: '#8888a8',
  border: '#d0d4e0',
  dark: '#f0f2f5',
  darker: '#e4e8f0',
  darkLight: '#f8f9fc',
};
