export const theme = {
  colors: {
    primary: '#7c4dff',
    primaryLight: '#b47cff',
    primaryDark: '#3f1dcb',
    secondary: '#00e5ff',
    dark: '#121212',
    darker: '#0a0a0a',
    darkLight: '#1e1e1e',
    success: '#00c853',
    danger: '#ff3d00',
    warning: '#ffab00',
    info: '#00b0ff',
    text: '#ffffff',
    textDim: '#b3b3b3',
    textSecondary: '#b0b0b0',
    textMuted: '#808080',
    border: '#333333',
    
    light: {
      background: '#f5f5f5',
      surface: '#ffffff',
      surfaceDark: '#e0e0e0',
      text: '#121212',
      textDim: '#424242',
      textSecondary: '#616161',
      textMuted: '#9e9e9e',
      border: '#e0e0e0',
    }
  },
  fonts: {
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semibold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    card: 12,
    input: 6,
    button: 8,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 8,
    },
  },
};
